# docker-compose.yml
version: '3.1'

services:
 consignment-cli: 
  build: ./consignment-cli
  environment:
   MICRO_REGISTRY: "mdns"
  networks: 
   - my-bridge

 consignment-service: 
  build: ./consignment-service
  ports:
   - 50051:50051
  environment:
   MICRO_RESIGTRY: "mdns"
   MICRO_ADDRESS: ":50051"
   DB_HOST: "datastore:27017"
  networks: 
   - my-bridge

 vessel-service:
  build: ./vessel-service
  ports:
   - 50052:50051
  environment:
   MICRO_ADDRESS: ":50051"
   MICRO_REGISTRY: "mdns"
   DB_HOST: "datastore:27017"
  networks: 
   - my-bridge

 database:
  image: postgres
  ports:
   - 5432:5432
  environment:
   POSTGRES_DB: "postgres"
   POSTGRES_USER: "postgres"
   POSTGRES_PASSWORD: "postgres"
  networks:
   - my-bridge

 user-service:
  build: ./user-service
  ports:
   - 50053:50051
  environment:
   MICRO_ADDRESS: ":50051"
   MICRO_REGISTRY: "mdns"
   DB_NAME: "postgres"
   DB_HOST: "database"
   DB_PORT: "5432"
   DB_USER: "postgres"
   DB_PASSWORD: "postgres"
  networks:
   - my-bridge

 user-cli: 
  build: ./user-cli
  environment:
   MICRO_REGISTRY: "mdns"
  networks: 
   - my-bridge

 datastore:
  image: mongo
  ports:
   - 27017:27017
  networks: 
   - my-bridge

networks:
 my-bridge:
  driver: bridge
